<%
try{int i=0;}
catch (Exception e)
{}

out.println(i);
%>